title: Bipin Singh Koranga
description: Personal website of Bipin Singh Koranga
google_site_verification: fnwKHv24OqFJR4E5dpCLXcM8EV5oiFutchz8TxoyWX8
logo: /assets/img/Bipin_sir_profile.jpeg
email: bskoranga@kmc.du.ac.in
location: New Delhi, India
